export const ALL_QUALIFICATIONS_START = 'ALL_QUALIFICATIONS_START';
export const ALL_QUALIFICATIONS_ERROR = 'ALL_QUALIFICATIONS_ERROR';
export const ALL_QUALIFICATIONS_SUCCESS = 'ALL_QUALIFICATIONS_SUCCESS';
export const ALL_QUALIFICATIONS_CHANGE_SORT = 'ALL_QUALIFICATIONS_CHANGE_SORT';
export const ALL_QUALIFICATIONS_DELETE = 'ALL_QUALIFICATIONS_DELETE';
