export const ALL_DEPARTMENTS_START = 'ALL_DEPARTMENTS_START';
export const ALL_DEPARTMENTS_ERROR = 'ALL_DEPARTMENTS_ERROR';
export const ALL_DEPARTMENTS_SUCCESS = 'ALL_DEPARTMENTS_SUCCESS';
export const ALL_DEPARTMENTS_CHANGE_SORT = 'ALL_DEPARTMENTS_CHANGE_SORT'; 
