export const PUBLICATION_SINGLE_START = 'PUBLICATIONS_SINGLE_START';
export const PUBLICATION_SINGLE_ERROR = 'PUBLICATION_SINGLE_ERROR';
export const PUBLICATION_SINGLE_SUCCESS = 'PUBLICATION_SINGLE_SUCCESS';
