export const PROFILE_REBUKES_START = 'PROFILE_REBUKES_START';
export const PROFILE_REBUKES_ERROR = 'PROFILE_REBUKES_ERROR';
export const PROFILE_REBUKES_SUCCESS = 'PROFILE_REBUKES_SUCCESS';
export const PROFILE_REBUKES_CHANGE_SORT = 'PROFILE_REBUKES_CHANGE_SORT';
