export const DELETE_PUBLICATION_START = 'DELETE_PUBLICATION_START';
export const DELETE_PUBLICATION_SUCCESS = 'DELETE_PUBLICATION_SUCCESS';
export const DELETE_PUBLICATION_ERROR = 'DELETE_PUBLICATION_ERROR';
