export const QUALIFICATIONS_SHOW_START = 'QUALIFICATIONS_SHOW_START';
export const QUALIFICATIONS_SHOW_ERROR = 'QUALIFICATIONS_SHOW_ERROR';
export const QUALIFICATIONS_SHOW_SUCCESS = 'QUALIFICATIONS_SHOW_SUCCESS';
export const QUALIFICATIONS_SHOW_CHANGE_SORT = 'QUALIFICATIONS_SHOW_CHANGE_SORT';
