export const EDIT_EDUCATION_LOAD_START = 'EDIT_EDUCATION_LOAD_START';
export const EDIT_EDUCATION_LOAD_ERROR = 'EDIT_EDUCATION_LOAD_ERROR';
export const EDIT_EDUCATION_LOAD_SUCCESS = 'EDIT_EDUCATION_LOAD_SUCCESS';
