export const ALL_REBUKES_START = 'ALL_REBUKES_START';
export const ALL_REBUKES_ERROR = 'ALL_REBUKES_ERROR';
export const ALL_REBUKES_SUCCESS = 'ALL_REBUKES_SUCCESS';
export const ALL_REBUKES_CHANGE_SORT = 'ALL_REBUKES_CHANGE_SORT';
export const ALL_REBUKES_DELETE = 'ALL_REBUKES_DELETE';
