export const DELETE_INTERNSHIP_START = 'DELETE_INTERNSHIP_START';
export const DELETE_INTERNSHIP_SUCCESS = 'DELETE_INTERNSHIP_SUCCESS';
export const DELETE_INTERNSHIP_ERROR = 'DELETE_INTERNSHIP_ERROR';
