export const ALL_PUBLICATIONS_START = 'ALL_PUBLICATIONS_START';
export const ALL_PUBLICATIONS_ERROR = 'ALL_PUBLICATIONS_ERROR';
export const ALL_PUBLICATIONS_SUCCESS = 'ALL_PUBLICATIONS_SUCCESS';
export const ALL_PUBLICATIONS_CHANGE_SORT = 'ALL_PUBLICATIONS_CHANGE_SORT';
export const ALL_PUBLICATIONS_DELETE = 'ALL_PUBLICATIONS_DELETE';
