export const DELETE_COMMISSION_START = 'DELETE_COMMISSION_START';
export const DELETE_COMMISSION_SUCCESS = 'DELETE_COMMISSION_SUCCESS';
export const DELETE_COMMISSION_ERROR = 'DELETE_COMMISSION_ERROR';
