export const ALL_USERS_START = 'ALL_USERS_START';
export const ALL_USERS_ERROR = 'ALL_USERS_ERROR';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_CHANGE_SORT = 'ALL_USERS_CHANGE_SORT';
export const ALL_USERS_DELETE = 'ALL_USERS_DELETE';
