export const INTERNSHIP_SINGLE_START = 'INTERNSHIP_SINGLE_START';
export const INTERNSHIP_SINGLE_ERROR = 'INTERNSHIP_SINGLE_ERROR';
export const INTERNSHIP_SINGLE_SUCCESS = 'INTERNSHIP_SINGLE_SUCCESS';
