export const PROFILE_PUBLICATIONS_START = 'PROFILE_PUBLICATIONS_START';
export const PROFILE_PUBLICATIONS_ERROR = 'PROFILE_PUBLICATIONS_ERROR';
export const PROFILE_PUBLICATIONS_SUCCESS = 'PROFILE_PUBLICATIONS_SUCCESS';
export const PROFILE_PUBLICATIONS_CHANGE_SORT = 'PROFILE_PUBLICATIONS_CHANGE_SORT';
