export const EDIT_QUALIFICATION_LOAD_START = 'EDIT_QUALIFICATION_LOAD_START';
export const EDIT_QUALIFICATION_LOAD_ERROR = 'EDIT_QUALIFICATION_LOAD_ERROR';
export const EDIT_QUALIFICATION_LOAD_SUCCESS = 'EDIT_QUALIFICATION_LOAD_SUCCESS';
