export const EDIT_COMMISSION_LOAD_START = 'EDIT_COMMISSION_LOAD_START';
export const EDIT_COMMISSION_LOAD_ERROR = 'EDIT_COMMISSION_LOAD_ERROR';
export const EDIT_COMMISSION_LOAD_SUCCESS = 'EDIT_COMMISSION_LOAD_SUCCESS';
