export const INTERNSHIPS_SHOW_START = 'INTERNSHIPS_SHOW_START';
export const INTERNSHIPS_SHOW_ERROR = 'INTERNSHIPS_SHOW_ERROR';
export const INTERNSHIPS_SHOW_SUCCESS = 'INTERNSHIPS_SHOW_SUCCESS';
export const INTERNSHIPS_SHOW_CHANGE_SORT = 'INTERNSHIPS_SHOW_CHANGE_SORT';
