export const EDIT_CATEGORY_LOAD_START = 'EDIT_CATEGORY_LOAD_START';
export const EDIT_CATEGORY_LOAD_ERROR = 'EDIT_CATEGORY_LOAD_ERROR';
export const EDIT_CATEGORY_LOAD_SUCCESS = 'EDIT_CATEGORY_LOAD_SUCCESS';
