export const PROFILE_EDUCATIONS_START = 'PROFILE_EDUCATIONS_START';
export const PROFILE_EDUCATIONS_ERROR = 'PROFILE_EDUCATIONS_ERROR';
export const PROFILE_EDUCATIONS_SUCCESS = 'PROFILE_EDUCATIONS_SUCCESS';
export const PROFILE_EDUCATIONS_CHANGE_SORT = 'PROFILE_EDUCATIONS_CHANGE_SORT';
