export const PROFILE_HONORS_START = 'PROFILE_HONORS_START';
export const PROFILE_HONORS_ERROR = 'PROFILE_HONORS_ERROR';
export const PROFILE_HONORS_SUCCESS = 'PROFILE_HONORS_SUCCESS';
export const PROFILE_HONORS_CHANGE_SORT = 'PROFILE_HONORS_CHANGE_SORT';
