export const PROFILE_INTERNSHIPS_START = 'PROFILE_INTERNSHIPS_START';
export const PROFILE_INTERNSHIPS_ERROR = 'PROFILE_INTERNSHIPS_ERROR';
export const PROFILE_INTERNSHIPS_SUCCESS = 'PROFILE_INTERNSHIPS_SUCCESS';

export const PROFILE_INTERNSHIPS_CHANGE_SORT = 'PROFILE_INTERNSHIPS_CHANGE_SORT';
export const PROFILE_INTERNSHIPS_HOURS = 'PROFILE_INTERNSHIPS_HOURS';
