export const PROFILE_QUALIFICATIONS_START = 'PROFILE_QUALIFICATIONS_START';
export const PROFILE_QUALIFICATIONS_ERROR = 'PROFILE_QUALIFICATIONS_ERROR';
export const PROFILE_QUALIFICATIONS_SUCCESS = 'PROFILE_QUALIFICATIONS_SUCCESS';

export const PROFILE_QUALIFICATIONS_CHANGE_SORT = 'PROFILE_QUALIFICATIONS_CHANGE_SORT';
export const PROFILE_QUALIFICATIONS_SET_NEXT = 'PROFILE_QUALIFICATIONS_SET_NEXT';
