export const ALL_COMMISSIONS_START = 'ALL_COMMISSIONS_START';
export const ALL_COMMISSIONS_ERROR = 'ALL_COMMISSIONS_ERROR';
export const ALL_COMMISSIONS_SUCCESS = 'ALL_COMMISSIONS_SUCCESS';
export const ALL_COMMISSIONS_CHANGE_SORT = 'ALL_COMMISSIONS_CHANGE_SORT';
export const ALL_COMMISSIONS_DELETE = 'ALL_COMMISSIONS_DELETE';
