export const ALL_CATEGORIES_START = 'ALL_CATEGORIES_START';
export const ALL_CATEGORIES_ERROR = 'ALL_CATEGORIES_ERROR';
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS';
export const ALL_CATEGORIES_CHANGE_SORT = 'ALL_CATEGORIES_CHANGE_SORT';
export const ALL_CATEGORIES_DELETE = 'ALL_CATEGORIES_DELETE';
