export const ALL_INTERNSHIPS_START = 'ALL_INTERNSHIPS_START';
export const ALL_INTERNSHIPS_ERROR = 'ALL_INTERNSHIPS_ERROR';
export const ALL_INTERNSHIPS_SUCCESS = 'ALL_INTERNSHIPS_SUCCESS';
export const ALL_INTERNSHIPS_CHANGE_SORT = 'ALL_INTERNSHIPS_CHANGE_SORT';
export const ALL_INTERNSHIPS_DELETE = 'ALL_INTERNSHIPS_DELETE';
