export const ALL_RANKS_START = 'ALL_RANKS_START';
export const ALL_RANKS_ERROR = 'ALL_RANKS_ERROR';
export const ALL_RANKS_SUCCESS = 'ALL_RANKS_SUCCESS';
export const ALL_RANKS_CHANGE_SORT = 'ALL_RANKS_CHANGE_SORT';
export const ALL_RANKS_DELETE = 'ALL_RANKS_DELETE';
