export const PUBLICATIONS_SHOW_START = 'PUBLICATIONS_SHOW_START';
export const PUBLICATIONS_SHOW_ERROR = 'PUBLICATIONS_SHOW_ERROR';
export const PUBLICATIONS_SHOW_SUCCESS = 'PUBLICATIONS_SHOW_SUCCESS';
export const PUBLICATIONS_SHOW_CHANGE_SORT = 'PUBLICATIONS_SHOW_CHANGE_SORT';
