export const ALL_EDUCATIONS_START = 'ALL_EDUCATIONS_START';
export const ALL_EDUCATIONS_ERROR = 'ALL_EDUCATIONS_ERROR';
export const ALL_EDUCATIONS_SUCCESS = 'ALL_EDUCATIONS_SUCCESS';
export const ALL_EDUCATIONS_CHANGE_SORT = 'ALL_EDUCATIONS_CHANGE_SORT';
export const ALL_EDUCATIONS_DELETE = 'ALL_EDUCATIONS_DELETE';
