export const APP_INITIALIZE_START = 'APP_INITIALIZE_START';
export const APP_INITIALIZE_SUCCESS = 'APP_INITIALIZE_SUCCESS';
export const APP_SET_ERROR = 'APP_SET_ERROR';
export const APP_RESET_ERROR = 'APP_RESET_ERROR';
