export const EDIT_PUBLICATION_LOAD_START = 'EDIT_PUBLICATION_LOAD_START';
export const EDIT_PUBLICATION_LOAD_ERROR = 'EDIT_PUBLICATION_LOAD_ERROR';
export const EDIT_PUBLICATION_LOAD_SUCCESS = 'EDIT_PUBLICATION_LOAD_SUCCESS';
