export const EDIT_DEPARTMENT_LOAD_START = 'EDIT_DEPARTMENT_LOAD_START';
export const EDIT_DEPARTMENT_LOAD_ERROR = 'EDIT_DEPARTMENT_LOAD_ERROR';
export const EDIT_DEPARTMENT_LOAD_SUCCESS = 'EDIT_DEPARTMENT_LOAD_SUCCESS';
