export const EDIT_INTERNSHIP_LOAD_START = 'EDIT_INTERNSHIP_LOAD_START';
export const EDIT_INTERNSHIP_LOAD_ERROR = 'EDIT_INTERNSHIP_LOAD_ERROR';
export const EDIT_INTERNSHIP_LOAD_SUCCESS = 'EDIT_INTERNSHIP_LOAD_SUCCESS';
