export const ALL_HONORS_START = 'ALL_HONORS_START';
export const ALL_HONORS_ERROR = 'ALL_HONORS_ERROR';
export const ALL_HONORS_SUCCESS = 'ALL_HONORS_SUCCESS';
export const ALL_HONORS_CHANGE_SORT = 'ALL_HONORS_CHANGE_SORT';
export const ALL_HONORS_DELETE = 'ALL_HONORS_DELETE';
