export const USER_MODAL_START = 'USER_MODAL_START';
export const USER_MODAL_ERROR = 'USER_MODAL_ERROR';
export const USER_MODAL_SUCCESS = 'USER_MODAL_SUCCESS';
export const USER_MODAL_SET_NAME = 'USER_MODAL_SET_NAME';
