export const QUALIFICATION_SINGLE_START = 'QUALIFICATION_SINGLE_START';
export const QUALIFICATION_SINGLE_ERROR = 'QUALIFICATION_SINGLE_ERROR';
export const QUALIFICATION_SINGLE_SUCCESS = 'QUALIFICATION_SINGLE_SUCCESS';
