export const DELETE_QUALIFICATION_START = 'DELETE_QUALIFICATION_START';
export const DELETE_QUALIFICATION_SUCCESS = 'DELETE_QUALIFICATION_SUCCESS';
export const DELETE_QUALIFICATION_ERROR = 'DELETE_QUALIFICATION_ERROR';
