name: Test app on push or PR
on:
    push:
        branches-ignore:
            - master

    pull_request:
        branches-ignore:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                persist-credentials: false

            - name: Install and test 🔧
              env:
                CI: ""
              run: |
                npm install
                npm run ci
